// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gobpklzixtnkdqrvhjbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvYnBrbHppeHRua2RxcnZoamJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzk3OTAsImV4cCI6MjA2MDY1NTc5MH0.D-dw73Ewi-FMHq0LweUMMZTAn9hvbT-5NqiWvtOqk6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);